services:
  - type: web
    name: packet-delay-analysis
    env: python
    buildCommand: |
      cd frontend && npm install && npm run build && cd ..
      cp -r frontend/build/* backend/static/
      cd backend && pip install -r ../requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
    healthCheckPath: /
    autoDeploy: true
